// <auto-generated />
using AnimeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimeApi.Migrations
{
    [DbContext(typeof(AnimeApiContext))]
    partial class AnimeApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimeApi.Models.Anime", b =>
                {
                    b.Property<int>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MovieCount")
                        .HasColumnType("int");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("int");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimeId");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            EpisodeCount = 720,
                            Genre = "Shonen",
                            MovieCount = 11,
                            SeasonCount = 30,
                            Studio = "TV Tokyo",
                            Title = "Naruto"
                        },
                        new
                        {
                            AnimeId = 2,
                            EpisodeCount = 1189,
                            Genre = "Fantasy",
                            MovieCount = 23,
                            SeasonCount = 13,
                            Studio = "OLM",
                            Title = "Pokemon"
                        },
                        new
                        {
                            AnimeId = 3,
                            EpisodeCount = 24,
                            Genre = "Comedy",
                            MovieCount = 0,
                            SeasonCount = 2,
                            Studio = "Madhouse",
                            Title = "One Punch Man"
                        },
                        new
                        {
                            AnimeId = 4,
                            EpisodeCount = 113,
                            Genre = "Shonen",
                            MovieCount = 3,
                            SeasonCount = 5,
                            Studio = "Bones",
                            Title = "Boku No Hero Academia"
                        },
                        new
                        {
                            AnimeId = 5,
                            EpisodeCount = 203,
                            Genre = "Shonen",
                            MovieCount = 0,
                            SeasonCount = 9,
                            Studio = "Artland",
                            Title = "Katekyo Hitman Reborn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
